# Generated by Django 3.1.6 on 2021-03-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutplans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='duration',
        ),
    ]
