# Generated by Django 3.1.6 on 2021-03-03 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutplans', '0002_remove_trainingplan_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='start_date',
        ),
    ]
